### ISSUE TITLE
Foxbot 0.792 Very Unstable

### ISSUE THREAD

**Issue by NukemD** [APGRoboCop/foxbot#6]
The latest Foxbot 0.792 release is extremely unstable. There's a note about it crashing listen servers, it crashes ALL servers, no matter if dedicated or listen, Linux or Windows.

I can't get my server to run more than 30 seconds or so before foxbot_mm.dll / foxbot.so causes the server to crash.

**Comment by APGRoboCop** [comment]
Did you get a debug log or any clues on how those crashes appear?

**Comment by NukemD** [comment]
Unfortunately no logs were produced on either Linux or Windows.

Windows would pop up a "this application has stopped working" dialog, and Linux would just have "./hlds_run segmentation fault at xxxx"

Windows error reporting came up once and in the stack trace, foxbot.dll was there. When I went back to the previous version 0.791, the crashes went away.

**Comment by APGRoboCop** [comment]
For Linux you need to install GDB and use it to find the cause of the crash. Then type this:-

`$ LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH" gdb ./hlds_linux`

Then this:-

`run -game tfc +map 2fort +ip xx.xx.xx.xx +port 27015 +maxplayers 24 -map 2fort +exec server.cfg` etc (ignore the "hlds_" part from "hlds_run". It will allow to backtrace but doesn't always work on some crashes.

**Comment by ForeskinJohn** [comment]
I've noticed that this instability has carried over to the latest build, ive since downgraded to 0.77 and have no issues whatsoever, I have also noticed that the bots in 0.77 complete objectives more often than in the latest build, I see a good future for later builds but TF Classic with bots is my preferred way to play when im not in tourney, ill be waiting for a fix in the near future, if not, the fact that this mod still gets updated is knowledge enough for me that some folks still care about this old game, lol ill never grow out of some good old team fortress, and i want to thank you RoboCop for keeping this game alive even after a majority of the community has left it to die, Ill always owe you a beer for that at least!
